CREATE DATABASE AGENDA;

CREATE TABLE USUARIO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(10) NOT NULL
);

ALTER TABLE USUARIO
MODIFY SENHA VARCHAR(15) NOT NULL;

ALTER TABLE USUARIO
MODIFY NOME VARCHAR(15) NOT NULL UNIQUE;

ALTER TABLE USUARIO
ADD EMAIL VARCHAR(150) NOT NULL UNIQUE;

INSERT INTO USUARIO VALUES (NULL, 'TH', 'THBC', 'thalles@gmail.com');